name: lint
on:
  - pull_request
  - push
jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run prettier
        env:
          # renovate datasource=npm depName=prettier
          PRETTIER_VERSION: 3.2.5
        run: |
          npx --yes prettier@$PRETTIER_VERSION --check . && exit 0
          npx prettier@$PRETTIER_VERSION --write
          git diff
          exit 1

  VerifyConfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install golangci-lint
        env:
          # renovate datasource=git-tags depName=https://github.com/golangci/golangci-lint
          GOLANGCI_LINT_VERSION: v1.57
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@$GOLANGCI_LINT_VERSION

      - name: Verify .golangci.yml file
        run: golangci-lint config verify -c .golangci.yml
